<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>12.0</LangVersion>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Sasd.Notes.Domain\Sasd.Notes.Domain.csproj" />
    <ProjectReference Include="..\Sasd.Notes.Application\Sasd.Notes.Application.csproj" />
    <ProjectReference Include="..\Sasd.Notes.Infrastructure\Sasd.Notes.Infrastructure.csproj" />
  </ItemGroup>
</Project>
